### ISSUE TITLE
Integration of cytoscape.js-undo-redo into cytoscape.js-expand-collapse

### ISSUE THREAD

**Issue by metincansiper** [iVis-at-Bilkent/cytoscape.js-expand-collapse#1]
It seem that we do not have this integration yet. In demo expand/collapse operations can be undone/redone. However, nearly everthing about this functionality is handled in 'demo.html'. However, 'demo.html' is just a kind of sample application. This should be handled in extension itself in a way that if 'undoable' option is not truthy then we should simply do the operation as we do now. However, if it is truthy, then we should call it through the cytoscape.js-undo-redo extension as it is done in 'demo.html' now.

**Comment by mrsfy** [comment]
In demo.html, there is only the usage of undo-redo and standard usage without undo-redo is in comments. Also, the implementation of undo-redo is in undoRedoUtilities.js. However, it would be better if I make demo.html undo-redo agnostic and demo-undoable.html with undo application.  Current implementation adds expand/collapse as actions to the undo-redo like the [default actions](https://github.com/iVis-at-Bilkent/cytoscape.js-undo-redo#default-actions-undoableredoable) of undo-redo.

Direct undo/redo implementation to the core functions of expand/collapse has some downsides. The main reason I didn't implemented in this way is that I realized that undo/redo of expand-collapse is too complex to be reimplemented in every use. Thus, I am planning a way to link actions in undo-redo. Currently, we cannot undo actions simultaneously and it causes many code-reuse problem. And by this update, default actions becomes more useful I think. But, in such updates expand/collapse must also be updated and I cannot see a way to keep it undo/redo agnostic after this update.
Also, undo-redo extension had become an action manager. Developer must use ur.do for each action. If we make an exception to expand/collapse by just using as eles.expand, it breaks the consistency.
