### ISSUE TITLE
Prevent disturbing shape on the expansion a node on the first time

### ISSUE THREAD

**Issue by raj-reactgeeks** [iVis-at-Bilkent/cytoscape.js-expand-collapse#101]
I am getting shape disturb issue when I click on plus icon of expand the node for the first time,
initially, it makes bigger shape then comes on an actual shape after some time might be in stop layout.

Expand is working very fine from the next expand time without disturbing ui only getting an issue at the first expand only.

Can anyone help me to get an exact shape in initial or fist time expand as well as coming in next expand?

**Comment by hasanbalci** [comment]
@raj-reactgeeks Please can you provide a JSFiddle or JSBin demo to reproduce this issue?
