### ISSUE TITLE
Weird behavior during edge collapse

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/cytoscape.js-expand-collapse#103]
While testing, I faced with the following: 
![Peek 2020-07-23 15-23](https://user-images.githubusercontent.com/22586369/88285975-af1b9e80-ccf8-11ea-8e95-ab097ce817b6.gif)

In this case, either only loops should be collapsed or none.

**Comment by canbax** [comment]
When I select edges with completely different source target pairs, it does not collapses. So to be more consistent I also didn't collapsed here.

**Comment by hasanbalci** [comment]
@canbax @ugurdogrusoz It's ok now, but I also realized that when we click on "Collapse all edges" in the demo, loops are not collapsed. Maybe we can collapse them as well. What do you think?

**Comment by canbax** [comment]
I think we should collapse the self loops as well.

**Comment by ugurdogrusoz** [comment]
Sure let's collapse them as well.

**Comment by hasanbalci** [comment]
There is still a small inconsistency: 
![Peek 2020-07-28 19-14](https://user-images.githubusercontent.com/22586369/88692390-ad8e1400-d106-11ea-88cd-aabb0a8b800c.gif)

Moreover, I think demo file checks whether there are at least two selected nodes when clicked on "Collapse edges between selected nodes" and "Expand edges between selected nodes". I think we can remove this check so that when we only select the node with self loops and click on these buttons, we can collapse and expand self loops.

**Comment by hasanbalci** [comment]
@canbax It seems working, thanks!
