### ISSUE TITLE
Improve demos

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-expand-collapse#118]
Let's improve the demos as follows:
- [x] 1. Make all demos' look & feel similar
- [x] 2. Combine node and edge expand/collapse demos
- [x] 3. Add import/export buttons to expose newly implemented load from/save to JSON functionality

**Comment by ugurdogrusoz** [comment]
Very nice. Additionally, let's do:
- [ ] 4. Add two buttons, under Nodes, at the beginning ("Add compound for selected" and "Remove selected compound") that
    o creates a compound from all nodes currently selected (nothing happens if all nodes aren't in the same graph) 
    o removes the selected compound moving its children to the owner graph of the compound (nothing happens if multiple selection or selection is not compound)

- [ ] 5. Slightly decrease paddings around buttons so they take up less space

**Comment by hasanbalci** [comment]
An additional point:
- [ ] When we apply Markov clustering on a graph, clustering button becomes disabled. When a new graph is loaded to the demo, clustering button should be enabled again so that user can apply clustering on the new graph.

**Comment by ugurdogrusoz** [comment]
@hasanbalci please check

**Comment by hasanbalci** [comment]
It seems ok, thanks @canbax
