### ISSUE TITLE
Option to Display number of collapsed nodes on collapsed groups

### ISSUE THREAD

**Issue by Alexithemia** [iVis-at-Bilkent/cytoscape.js-expand-collapse#120]
Would you be able to implement an option for the collapsed groups to display how many nodes are collapsed within it?

Or do you know of an easy way to achieve this? I am already using the label normally.

![image](https://user-images.githubusercontent.com/44597137/105738489-b0729180-5efc-11eb-8d82-3438ca3f0e96.png)

**Comment by ugurdogrusoz** [comment]
@canbax The users should be able to access number of such nodes, right?

**Comment by canbax** [comment]
When the nodes are collapsed, the information about the collapsed children is stored inside their data with a property named `collapsedChildren` (both edges and nodes inside) So the API users can get this info easily. So the API user can show this information in their application. (a sample case would be showing this information inside the "Object" tab in [newt](http://web.newteditor.org/))

This information could be shown in different ways. One way is to show it like in the first image, like a badge. It can be showed like we show expand cue image.

It can also be showed on the label. Like for the image below the label could be `Ministry of Commerce (2)`. It can be shown only when the collapsed node is selected.

**Comment by Alexithemia** [comment]
I did see how I would get the number from the collapsed node, and I will need to filter out only the nodes as edges are also in the collapsed children collection, adding it to the label would be easy but the badge look is what we want.

How would we go about showing that as a badge like the cue image?

**Comment by ugurdogrusoz** [comment]
That's a Cytoscape.js core issue not related to this extension. You could use background images for instance.
