### ISSUE TITLE
Expanding all the collapsed nodes causes a bad layout

### ISSUE THREAD

**Issue by canbax** [iVis-at-Bilkent/cytoscape.js-expand-collapse#123]
- open [https://codepen.io/canbax/project/editor/XWedGa](https://codepen.io/canbax/project/editor/XWedGa)
- Click to "Add Labels" and then "Expand All Nodes"
- You will see that the layout algorithm (fcose in this case) is not giving good results.

- refresh the page and then click to "Expand All Nodes". This time you will see the layout is fine.

I observed another strange thing:
- When nodes are expanded, compounds somehow do not show in the right positions. If you comment out the line https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/blob/unstable/src/elementUtilities.js#L47 which is `layout.run();` the layout won't be called. This causes somehow compound nodes aren't containing their children https://user-images.githubusercontent.com/8426741/110345643-dcc31700-803f-11eb-8650-b3dc759d3478.png If I go and click to the compounds one by one so that the positions and sizes of these compounds will be right and then I run layout. This time layout also seems fine.

There is also similar info about this issue https://github.com/ugurdogrusoz/visuall/issues/353

**Comment by hasanbalci** [comment]
This should be fixed now. @canbax @ugurdogrusoz Can you please verify?

**Comment by canbax** [comment]
I checked this with the codepen sample (I used the latest cytoscape-expand-collapse.js in the sample) It seems fixed there.

Also, I tested on http://visuall.herokuapp.com/ It also seems fine.
