### ISSUE TITLE
Losing edges bug

### ISSUE THREAD

**Issue by FerMG** [iVis-at-Bilkent/cytoscape.js-expand-collapse#124]
Hello, is this a bug?

![ezgif-2-4875f5e4355d](https://user-images.githubusercontent.com/13823925/122499924-2a003e80-cfc8-11eb-9161-9c7a1a797fd3.gif)

**Comment by ugurdogrusoz** [comment]
Yes, this is a known [issue](https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/issues/100). Closing this to avoid redundancy.
