### ISSUE TITLE
Undefined variable in 'expandCollapseUtilities.js'

### ISSUE THREAD

**Issue by bensonnw** [iVis-at-Bilkent/cytoscape.js-expand-collapse#133]
Go to line 745 of the file, 

`edgesTypeField = options.edgeTypeInfo instanceof Function ? edgeTypeField : options.edgeTypeInfo;`, the variable `edgeTypeField` after the question mark is undefined, it should be `edgesTypeField`

There is a runtime error whenever using option with `edgeTypeInfo`

**Comment by hasanbalci** [comment]
@bensonnw Thanks for noticing us. The bug is fixed in the unstable branch and will be available in the master branch with the next release.
