### ISSUE TITLE
Disabling expand/collapse cue breaks Cytoscape

### ISSUE THREAD

**Issue by somedmguy** [iVis-at-Bilkent/cytoscape.js-expand-collapse#14]
Passing `cueEnabled: false` to `cy.expandCollapse()` breaks Cytoscape.

I suspect this is due to calling `cy.off()` with undefined event handlers causing all handlers (including the core's) to be unbound.

**Comment by metincansiper** [comment]
@somedmguy thak you for notifying and reporting this bug. I think that the problem was related to the point that you mentioned. The problem seems to be fixed now. We can close the issue if you are agree.
