### ISSUE TITLE
Expand cues are drawn for hidden collapsed nodes

### ISSUE THREAD

**Issue by somedmguy** [iVis-at-Bilkent/cytoscape.js-expand-collapse#15]
add `'visibility': 'hidden'` to the collapsed node style in the demo to get:

![image](https://cloud.githubusercontent.com/assets/21342204/18098591/bcb3020e-6e97-11e6-8470-c87a9a2a7d73.png)

**Comment by ugurdogrusoz** [comment]
I don't know if it's related but I also notice that the cues are not drawn in correct locations during animation or some interactive operations.

**Comment by metincansiper** [comment]
@somedmguy @ugurdogrusoz now do not draw expand cues consistenly. Therefore, I think that this not be a problem.  I think that when you hide a node in the way that you described expand cue of that node (if it is rendered on that time) will not disappear instantly, but it will dissappear when you move your mouse cue in your cytoscape container.

As far as I know in cytoscape there is no special event triggered on hide action (I think that it is just a style change). Therefore we cannot listen such an event and solve that little problem (the one that I decribed above). We can consider them if you have any kind of advice about this. However, I think that the main problem that you described no more exists.
