### ISSUE TITLE
HTML example

### ISSUE THREAD

**Issue by botev** [iVis-at-Bilkent/cytoscape.js-expand-collapse#19]
I know this is a pretty dumb question, but I found so far the easiest way to get started with something is by having an example to read, e.g. for instance how to easily make something press able so I can use your extension and so on. 

Again, this is probably very straightforward, but I haven't really programmed too much with js as I'm a researcher, but want to use your extension for some hierarchical visualization. So far cytoscape worked really great for this, but we need a way of managing the complexity.

**Comment by ugurdogrusoz** [comment]
@botev Expand-collapse is a major mechanism for managing complexity of your networks if you have a way to represent your relational information using nesting relations (i.e. compounds). For instance, if you have 100 high level nodes, each containing another 100 nodes as children (a total of 10K nodes), trying to visualize and analyze all this data is rather complex. However, if you display the graph in a format, where compound nodes are initially collapsed, then you only have 100 nodes in your graph. Later on, the user may expand these high level nodes on demand and focus on desired parts. Let us know if you have any questions about the usage of this extension for this purpose.

**Comment by botev** [comment]
Yep I got it working. Sorry for some reason initially I missed that there is an demo.html. Must have been too late I guess. 

I have only one, like a suggestion. Currently when you expand a node you have to redraw the graph based on the layout. It would be nice if it is possible to expand the node approximately at its location without rearranging the whole graph. Or maybe this is an issue only with the dagre layout.

**Comment by ugurdogrusoz** [comment]
You don't have to perform layout after expand-collapse; it's optional. See "layoutBy" option of this extension.

**Comment by botev** [comment]
Hmm, to some extend what I have in mind is sort of on the lines:
1. When you expand you use the layoutBy only to arrange the nodes in the expanded node, while for instance anchoring its left top corner and all other nodes. After this any nodes outside nodes which turns out to be inside the area of the expanded node should be pushed away outside. 

Atm, the expand makes redraw not only the expanded node, but the whole graph. Could you point me out to where is the code for redrawing the graph, I might be able to implement this myself and just add one more option to the extension.

**Comment by ugurdogrusoz** [comment]
Pushing neighbors away is done by "fisheye" option, which is already true by default. So all you have to do should be to set "layoutBy" null to avoid succeeding incremental layout. You shouldn't have to arrange the nodes inside the expanded node since presumably they were OK before they were collapsed. If you have to rearrange them however, you may do so by calling layout only on this child nodes (assuming your choice of layout support partial layout). Any particular reason you're using dagre? With compound nodes, I think you should definitely use "cose-bilkent" (not "cose").

**Comment by botev** [comment]
Hmm for some reason atm if I set the "layoutBy" to null, collapse the nodes and then expand them I get all nodes on top of each other? Is there a flag for retaining their positions? I will also try "cose-bilkent", I tried "cose" but found "dagre" much better, but maybe your suggestion is even better.

**Comment by ugurdogrusoz** [comment]
@metincansiper will answer your question about laying out a part of a graph.

Regarding layout style to use, dagre seems to have done a very nice job in your particular example to my surprise since I thought it didn't handle compounds! I would be surprised to find out it handle arbitrary nesting levels and inter-graph edges though. With current cose-bilkent you cannot impose a hierarchy on your graph.

**Comment by botev** [comment]
Yes, I think I've seen some quite bad renderings from dagre as well. I guess if there was something like a "tree" layout where you have some roots and layout the DAG according to levels based on the edges directions is what I need, but that might be a bit too much sideways from what I'm doing to write it on my own. I will keep in mind and explore both of the layouts and pick whichever on average seems to do better. 
Anyway thanks a lot for the fast responses, was really helpful and I'm quite pleased with how easy and fast I managed to achieve what I wanted.

**Comment by metincansiper** [comment]
@botev you can set 'layoutBy' parameter as just layout options or whole layout function. I think that in your case it may be a function and you can use it in the following way:

layoutBy: function() {
    // eles are the elements to layout
    eles.layout(//your layout options here)
}

Not that this extension enables users to set the options after the initilazitaion as well. If you want to set this option after initilization you can use the following:

cy.setExpandCollapseOption('layoutBy', yourLayoutByFunction);

**Comment by botev** [comment]
@metincansiper I think that did what I wanted. I have two questions:
1. How do I pass named arguments to the function ".layout()"? or where can I find the correct ordering of the parameters.
2. With this I get a very weird behaviour - when I press the collapse icon, the node collapses as desired. However it seems that the js does not recognize the mouserelease event, and essentially the node gets locked to the mouse movement (e.g. after the click until you make another click however you move the mouse the collapsed node follows the mouse movements). Can this be avoided?

**Comment by botev** [comment]
So let me make it more clear in what I want to do:

Inside this function how do I get only the children of the expanded node, such that I specify the layout only for them and not modify anything outside this node.

**Comment by ugurdogrusoz** [comment]
Please refer to Cytoscape.js documentation!
