### ISSUE TITLE
Event callback signature in docs

### ISSUE THREAD

**Issue by maxkfranz** [iVis-at-Bilkent/cytoscape.js-expand-collapse#2]
`cy.on("afterExpand", function(node) { })` should be `cy.on("afterExpand", function(event) { var node = this; ...  })`

**Comment by mrsfy** [comment]
It would be better, thanks but there is a minor issue.
Now, `cy.nodes().on("afterExpand", function(event) { var node = this; ... })` works properly but `cy.on("afterExpand", function(event) { var node = this; ... })` _this_ value is not a node. It is a scope including _private & one of my variables.

I am using `node.trigger("afterExpand")` to emit event. I also tried `cy.trigger.call(node, "afterExpand)` but result was the same.

**Comment by maxkfranz** [comment]
Typo: `cy.on("afterExpand", function(event) { var cy = this; ... })`

If you want the node, you have to bind directly to the node or use a delegate selector.

I've confirmed this working fine in the console:

```
cy.on('foo', 'node', function(e){ console.log( e, this ) });
Core {_private: Object}
cy.nodes()[0].trigger('foo')
VM488:1 Event {originalEvent: Object, type: "foo", cy: Core, cyTarget: Element, cyPosition: undefined…} Element {0: Element, length: 1, _private: Object}
Element {0: Element, length: 1, _private: Object}
```

**Comment by mrsfy** [comment]
After the commit above, it works now as expected.
