### ISSUE TITLE
Problems with AMD scope

### ISSUE THREAD

**Issue by djangosdk** [iVis-at-Bilkent/cytoscape.js-expand-collapse#22]
when using AMD, functions are under scope not under global window.

This should work but does not , _ReferenceError: cy is not defined_
```js  
 require(['jquery', 'cytoscape', 'cytoscape-expand-collapse'], function ($, cytoscape, expandCollapse) {
   expandCollapse(cytoscape, $); // register extension
   $('#cy').cytoscape({
     ready: function () {
       var cy = this; // scoped cy
       cy.expandCollapse();
     }
   });
 });
```
This one works because of ``` window.cy = this; ```
```js  
 require(['jquery', 'cytoscape', 'cytoscape-expand-collapse'], function ($, cytoscape, expandCollapse) {
   expandCollapse(cytoscape, $); // register extension
   $('#cy').cytoscape({
     ready: function () {
       window.cy = this; // expandCollpase only works if this line is defined
       var cy = this;
       cy.expandCollapse();
     }
   });
 });
```

This is confusing because there could be multiple instances of cy running in tabs for example.
expandCollpase should accept the cy it is being provided with, instead of looking for ```window.cy```

**JSFIDDLE:** https://jsfiddle.net/bababalcksheep/ypgdkcup/3/

**Comment by djangosdk** [comment]
this plugin does not work because of  ```window.cy``` with AMD when using bootstrap tabs for example, where each tab created dynamically has a cytoscape js and only last tab gets this control and rest don't

**Comment by metincansiper** [comment]
@djangosdk Thank you for repoting the problem. I think that the problem was not specific to AMD. It seems to be solved now. If you are agree we can close the issue.

**Comment by djangosdk** [comment]
@metincansiper . Fixes error now.
Seems to fix issue but i am still unable to make it work with tabs. I think i will find out more and post new issue if any

**Comment by metincansiper** [comment]
@djangosdk thanks it would be great.
