### ISSUE TITLE
Expose as module

### ISSUE THREAD

**Issue by ripfire44** [iVis-at-Bilkent/cytoscape.js-expand-collapse#33]
I notice there is a `src/index.js` file that can expose the project as a module. Why isn't this used as `main` in the `package.json`?

**Comment by kinimesi** [comment]
Fixed at unstable https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/commit/57d6753ceb8099575d4d1151f50e9afea5375df8

@ripfire44  Can you close the issue?

**Comment by ripfire44** [comment]
Once you expose it as a module, you need to fix the JQuery dependency on `cueUtilities.js`.  There's no guarantee that the `$` will be available on the global scope.
