### ISSUE TITLE
Consistent distribution guideline drawing

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-expand-collapse#36]
We should draw distribution guidelines consistently when the dragged node is in between two nodes (same as equally distanced outside of two nodes)

**Comment by kinimesi** [comment]
@ugurdogrusoz  Why an issue related to [cytoscape.js-grid-guide extension](https://github.com/iVis-at-Bilkent/cytoscape.js-grid-guide) is opened under expand-collapse extension?

**Comment by ugurdogrusoz** [comment]
https://github.com/iVis-at-Bilkent/cytoscape.js-grid-guide/issues/19
