### ISSUE TITLE
Neither demo-undoable.html nor demo.html works??

### ISSUE THREAD

**Issue by 21thermostat** [iVis-at-Bilkent/cytoscape.js-expand-collapse#37]
I just download the master.zip. But the demo page does not work.  I got the below error:
Uncaught TypeError: $container.cytoscape is not a function
    at init (cueUtilities.js:195)
    at module.exports (cueUtilities.js:292)
    at u.expandCollapse (index.js:187)
    at HTMLDocument.<anonymous> (demo-undoable.html:96)

**Comment by kinimesi** [comment]
@21thermostat demo files are broken in Cytoscape v3.0.0. Currently, we are updating our libraries. Temporarily you can run the demo files by changing line 11 in `demo.html` and `demo-undoable.html` to:

```javascript
<script src="http://cytoscape.github.io/cytoscape.js/api/cytoscape.js-2.7.11/cytoscape.min.js"></script>
```

**Comment by kinimesi** [comment]
@21thermostat should be fixed in https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/commit/1baafb1f6fa816619cf92e1121703a54a53cba4b Can you verify and close? Thanks.

**Comment by 21thermostat** [comment]
Thanks for fast fix. Now it works fine.
