### ISSUE TITLE
Error in expand node operation

### ISSUE THREAD

**Issue by metincansiper** [iVis-at-Bilkent/cytoscape.js-expand-collapse#4]
In my local "demo.html" copy I added "'content': 'data(id)'" to the node style to be able to indetify the id's of the nodes.

I go through the following steps in order,

collapse p0
collapse n2
collapse n3
expand n2

Then the last expand operation is failed with the following warnings,

![expand-collapse-errors](https://cloud.githubusercontent.com/assets/6534865/16804569/19f4f9a2-4915-11e6-9b0f-0818ec48f181.PNG)

**Comment by ugurdogrusoz** [comment]
I don't know if this is the same bug but here is how I get one with the daily editor build:
- collapse the compound in the middle (of the default map)
- collapse the compound on the right
- expand the collapsed node in the middle; fish eye works file (neighboring nodes are pushed away) but expand doesn't take place (stays collapsed). see the console for crash details.

**Comment by aindlq** [comment]
jfyi, I'm getting the same error time to time. Will try to reproduce with minimal example.

**Comment by ugurdogrusoz** [comment]
thanks. actually, fyi, recently we refactored some functionality out of SBGNViz.js as Cytsocape.js extensions, and during this transitions some bugs were introduced.

**Comment by aindlq** [comment]
I've just tried to reproduced, and it is definitely stochastic issue, kind of a weird race condition. Because it happens to me time to time, but not always. Even when I do exactly same set of actions.

**Comment by ugurdogrusoz** [comment]
A simpler example to reproduce this bug:
- load attached map
- collapse C1
- collapse C2
- expand C1 (it won't expand)
[expand-bug.sbgnml.txt](https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/files/368671/expand-bug.sbgnml.txt)

**Comment by aindlq** [comment]
I've tried to debug it. The issue is somewhere inside cytoscape restore function.

One obvious bug is here https://github.com/cytoscape/cytoscape.js/blob/b12d751d39e5a0cb9b8edd92d9dda10c2cbebe4c/src/collection/index.js#L306, `l` variable is fixed in the begginig of for loop, but then removeFromElements can change the size of the elements collection. But `l` will not be re-evaluated.

I'm trying to understand if this is the main issue.

**Comment by aindlq** [comment]
Ok, found the pattern. It fails when there outgoing edges from the nodes inside one collapsed compound node to nodes inside other collapsed compound node.

E.g: http://jsbin.com/nogasigaya/edit?html,output
wait until everything is collapsed and then try to expand W3C1 node.

**Comment by ugurdogrusoz** [comment]
Thanks for you help @aindlq. We think we know the problem and we're trying to fix it (not a straightforward one). Thanks for your patience.

**Comment by metincansiper** [comment]
We fixed this bug and commited the changes. #6 seems to be solved too with these commits. @ugurdogrusoz if you approve we can publish new version.

**Comment by ugurdogrusoz** [comment]
Great job @metincansiper @mrsfy. @aindlq, could you confirm as well?

**Comment by aindlq** [comment]
Indeed a great job. Thank you! 

Can confirm that both have been fixed, see http://jsbin.com/kevujuhoxe/edit?html,output.

**Comment by ugurdogrusoz** [comment]
This example works fine as well. Btw, any particular reason you have animation=true instead of animation=end for your layouts in this example? I suggest you try it.

**Comment by aindlq** [comment]
No good reason, I think I simply copy-pasted it from README.md
