### ISSUE TITLE
Can expandcollapse.afterexpand be fired after nodes are repositioned?

### ISSUE THREAD

**Issue by d2fong** [iVis-at-Bilkent/cytoscape.js-expand-collapse#44]
The expandcollapse.afterexpand event is fired before the node positions are corrected.  Is it possible to fire this after the node positions are corrected?

i.e switch the order of line 31 and line 34? 

https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/blob/master/src/expandCollapseUtilities.js#L31

https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/blob/master/src/expandCollapseUtilities.js#L34

**Comment by kinimesi** [comment]
@d2fong Can you give more details on what you are trying to do and how will swapping those lines help you achieve it?

**Comment by d2fong** [comment]
@kinimesi 

It doesn't matter that much to me now because I am using ```layoutBy```,  but it seems strange to fire this event before updating the positions, because to me the meaning of ```afterexpand``` means the event is fired after the whole expand operation is finished.  i.e the node is restored and it's children are restored and properly positioned. 

I'd say maybe you could document your meaning of ```afterexpand``` and the context in which it is called.  e.g this event is fired after the node children are restored, but before their positions are updated.  Or if you don't want people to use ```afterexpand```, maybe just remove it from the documentation.

**Comment by ugurdogrusoz** [comment]
@kinimesi what do you think?

**Comment by kinimesi** [comment]
@ugurdogrusoz Because *someone* run into a problem with the order of fired events, it does not mean that the order is wrong. `afterexpand` event is fired just after the node is expanded. The positioning of nodes is a post process, which is done after node is expanded. So firing `afterexpand` event, after doing the positioning is wrong and meaningless.

**Comment by d2fong** [comment]
@kinimesi 

First of all.  I said in my response that you don't have to change it.  All I am saying is that your documentation is misleading.

Take a look at your documentation for the ```layoutby``` option and the ```afterexpand``` event:

Here is the documentation for ```layoutby```:
```js
      layoutBy: null, // to **rearrange after expand/collapse**. It's just layout options or whole layout function. Choose your side!
```

Here is the documentation for ```afterexpand```:
```js
cy.nodes().on("expandcollapse.afterexpand", function(event) { var node = this; ... }) **Triggered after a node is expanded**
```

This could imply to people that these two things do something similar when in reality they will not.  Because one happens before the nodes are repositioned and the other happens after.

Now you will say that after expand is not the same as after a node is expanded.  But that then implies that the user has to know that there exists a post processing step.

But again, if I search for any terms such as ```post process```, ```reposition```, or ```position```.   Nothing comes up in the documentation.  

What I am trying to get at this is that you probably know the codebase for this extension really well.  I bet most users do not.  So I hope you can understand now why someone might get confused when you assume that users have to know specific implementation details that have not been documented at all to use this extension _properly_.

**Comment by ugurdogrusoz** [comment]
@d2fong we moved the location of the trigger. we also made a note as follows in the documentation (unstable branch):

Notice that following events are performed for *each* node that is collapsed/expanded. Also, notice that any post-processing layout is performed *after* the event.

Please let us know if this is more reasonable now.
