### ISSUE TITLE
Hide edges for collapsed nodes.

### ISSUE THREAD

**Issue by aindlq** [iVis-at-Bilkent/cytoscape.js-expand-collapse#5]
Would it be possible to add the ability to hide all edges for collapsed nodes? Would you like to have this functionality as part of this plugin?

If so I can provide a PR, if you could point me to the proper places. From a quick look it seems that I just need to hook into simpleCollapseNode and simpleExpandNode and hide/show all incoming/outgoing edges.

Or maybe in case of this option we can just make nodes invisible, and edges will not be displayed by default. Any ideas, suggestions are welcome.

**Comment by aindlq** [comment]
Thank you for the response. I didn't know abou the ability to style "meta" edges. I think it is sufficient for my use case to hide/style them differently if needed.

One issue that I observe that all edges for nodes related to compound nodes are marked with "meta" class.
E.g if all compound nodes are expanded so there are no visible "meta" edges for compound nodes. Edges for nodes which are inside compound node are still marked as "meta". I think that "meta" marker should be applied only to artificial edges. Is it a bug?

**Comment by ugurdogrusoz** [comment]
If so, it's a bug. We'll look into this.
