### ISSUE TITLE
How to start with nodes collapsed?

### ISSUE THREAD

**Issue by 0xdabbad00** [iVis-at-Bilkent/cytoscape.js-expand-collapse#55]
My dataset has a large number of nodes which takes a long time to load.  I was thinking it would load faster if I started with some of the compound nodes collapsed. How can I go about doing this?  Does this need to happen when cytoscape is initialized or does it happen in this extension?

**Comment by kinimesi** [comment]
@0xdabbad00 it does not happen in extension level. One way of implementing this is to call `api.collapseAll` or `api.collapseRecursively` during initialization. Provide `api.collapseAll` or `api.collapseRecursively` as `ready` option of layout. You can also write a simple layout which calls those functions.

Here is a working [example](http://www.pathwaycommons.org/pathways/#/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-6804756) in Pathway Commons. You can analyze the source code [here](https://github.com/PathwayCommons/pathways-search/).

**Comment by Does666** [comment]
Is it posssible to show collapsed nodes at initial state? When expand a node, load children nodes of expanded node?
