### ISSUE TITLE
Cue position does not adjust to the top-left corner of the compound node 

### ISSUE THREAD

**Issue by RosaRomeroGomez** [iVis-at-Bilkent/cytoscape.js-expand-collapse#59]
I've been working with the Cose-Bilkent layout lately and I've just added this plug-in to be able to collapse and expand compound nodes. It seems that everything works fine but I think there is some issue with some padding for the cues. It seems to get placed outside of the compound node so the action doesn't get trigger. It seems to get better when I zoom in to certain level so the cue finally gets placed inside the compound node. Please, find attached below some screenshots of this issue. The first one is an example of the original placement of the cue on a compound node when the graph gets displayed. The second one is the result of zooming in. Any clue of why is this happening? I'm using the following parameters for the layout: 
```
   layout_params = {
              name: 'cose-bilkent',
              animate: false,
              randomize: true,
              tilingPaddingVertical: 20,
              tilingPaddingHorizontal: 20,
          }

```
<img width="169" alt="screen shot 2018-09-19 at 10 51 05 pm" src="https://user-images.githubusercontent.com/10552785/45793246-40361000-bc5f-11e8-8f05-13a166ab7ce1.png">
<img width="461" alt="screen shot 2018-09-19 at 10 51 14 pm" src="https://user-images.githubusercontent.com/10552785/45793250-43c99700-bc5f-11e8-8a73-9431c74e6d54.png">

Many thanks!

**Comment by ugurdogrusoz** [comment]
@RosaRomeroGomez This shouldn't happen if you're using the default options documented in the extension (see README here https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse). You can adjust the position of the expand/collapse visual cue using this option: expandCollapseCuePosition (could provide a function for it as well).
If you can't figure out your problem, perhaps you could provide a JS Fiddle to reproduce your problem.

**Comment by RosaRomeroGomez** [comment]
Thanks @ugurdogrusoz for your quick response. I'm using the default options documented in the extension but I suspect there is something weird going on with the zooming capabilities. This is how I initialize the extension:

      var expandCollapse_defaults = {
        layoutBy: null, // to rearrange after expand/collapse. It's just layout options or whole layout function. Choose your side!
        // recommended usage: use cose-bilkent layout with randomize: false to preserve mental map upon expand/collapse
        fisheye: true, // whether to perform fisheye view after expand/collapse you can specify a function too
        animate: true, // whether to animate on drawing changes you can specify a function too
        ready: function () { }, // callback when expand/collapse initialized
        undoable: false, // and if undoRedoExtension exists,

        cueEnabled: true, // Whether cues are enabled
        expandCollapseCuePosition: 'top-left', // default cue position is top left you can specify a function per node too
        expandCollapseCueSize: 30, // size of expand-collapse cue
        expandCollapseCueLineSize: 20, // size of lines used for drawing plus-minus icons
        expandCueImage: undefined, // image of expand icon if undefined draw regular expand cue
        collapseCueImage: undefined, // image of collapse icon if undefined draw regular collapse cue
        expandCollapseCueSensitivity: 2 // sensitivity of expand-collapse cues
      };
      cy.expandCollapse(expandCollapse_defaults); 
      let api = cy.expandCollapse('get');`

I've increased the cue size a bit and it seems to adjust better (I know this is not an ideal solution but it works for now while I find another solution). If I wanted to add another cue image instead of the default one, would it suffice just to include the path to the cue? Something like: `expandCueImage: /path/to/image.png` Thanks again!

**Comment by kinimesi** [comment]
@RosaRomeroGomez as @ugurdogrusoz mentioned this should not happen. Paddings are taken into consideration in default position calculation. See our [demo](https://rawgit.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/master/demo.html) - cues are positioned correctly independent of zoom level. Can you provide a minimal JS Fiddle which reproduces your problem?

**Comment by Does666** [comment]
Would it suffice just to include the path to the cue? Something like: expandCueImage: /path/to/image.png ? I have tried but not works well.
