### ISSUE TITLE
"meta" class is not removed

### ISSUE THREAD

**Issue by metincansiper** [iVis-at-Bilkent/cytoscape.js-expand-collapse#6]
As @aindlq pointed out in #5, when a node is collapsed and expanded back the "meta" edges, created upon collapse operation, are removed and the original edges are restored back. However, unexpectedly these original edges have "meta" class though they are not "meta" edges.

**Comment by mrsfy** [comment]
Collapse operation simply works as following for edges as I understood:
1. Add "meta" classes to connected edges.
2. Remove connected edges
3. Add new "meta" edges to collapsed compound with meta class.

I commented out 1st step. But it might be required for something else that I don't know. Please check demo.html. 
I colored meta edges as red in demo.html.

**Comment by metincansiper** [comment]
I think that it is working fine in "demo.html".

"meta" class is already being added to the edges which are supposed to be "meta" while they are just created. Therefore, as you said the first step is not needed and it seems that it is the cause of the bug. 

You can close the issue when you publish the new version.

**Comment by mrsfy** [comment]
To fix #4 , we need to make significant changes on "meta" edge specification. Thus, we agreed on that we should publish new version for #4. Till then, this issue should be open as a reference.
