### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by HochmanEyal** [iVis-at-Bilkent/cytoscape.js-expand-collapse#62]
When calling getCollapsedChildrenRecursively on an empty collection, i'm getting an
`Uncaught TypeError: Cannot read property 'length' of undefined`
Exception in the console.
I managed to recreate the issue in [jsFiddle](http://jsfiddle.net/eto18f9q/).

I looked at the call stack and it seems that `node.data('collapsedChildren');` returns undefined and when `length` is called on the returned value an exception is thrown.

I actually ran into this problem before when the collection was not empty and `node.data('collapsedChildren');` returned null.

As a workaround I iterated over the collection and checked the return value of `node.data('collapsedChildren');` for each node.
Wherever I got null I replaced it with an empty array and it solved the issue.

**Comment by kinimesi** [comment]
I added a sanity check to handle this case, but `getCollapsedChildrenRecursively` should be called on a **single** collapsed node.

https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/blob/8a2e4157def5613e0e477e393dc2c0720e41c032/src/expandCollapseUtilities.js#L652

Calling it on a collection of nodes will return the collapsed children of the first element in the collection. You need to iterate over your collection and call `getCollapsedChildrenRecursively` on each node. Before that, you can filter the nodes which are expandable by using `api.expandableNodes`.

If this solves your problem, please close the issue.
