### ISSUE TITLE
Event "expandcollapse.afterexpand" is triggered multiple times

### ISSUE THREAD

**Issue by HochmanEyal** [iVis-at-Bilkent/cytoscape.js-expand-collapse#64]
If a collapsed node (let's call it **A**) listens to "afterexpand" event and it's parent listens to it too, then expanding **A** causes the "afterexpand" event to fire on **A** twice (and if **A**'s parent also had a parent which listens to this event, it would be fired three times. I also _assume_ that the same thing happens for "beforeexpand" and for the collapse events as well).

I managed to duplicate the issue in [JsFiddle](http://jsfiddle.net/je4gs7Lr/).

**Comment by kinimesi** [comment]
The event is not triggered multiple times, you attach **multiple listeners** to a single node.

When an event is attached to a compound node by using `eles.on`, the event propagates to the children of that compound node as well.

In your example, if you try the following code, when node A is clicked the message will be printed once, when node B is clicked the message will be printed twice, and when node C is clicked it will be printed three times, and so on:
```js
window.cy.nodes().on("tap", function(event) {
    console.log("tapped")
})
```
If you attach the events to the core, it will always be triggered only once:
```js
window.cy.on("tap", "node", function(event) {
    console.log("tapped")
})
```

Please close the issue if this solves your problem.

**Comment by HochmanEyal** [comment]
I see the problem with my code now, thank you very much!
