### ISSUE TITLE
How to only run layout on subgraph of expanded/collapsed node

### ISSUE THREAD

**Issue by utkarshagarwal01** [iVis-at-Bilkent/cytoscape.js-expand-collapse#66]
When using expand collapse with dagre layout, on expanding a node, the two subtrees from the root often switch position. This looks visually very confusing.

To stop this behavior, I am trying to run the layout only on the subgraph of the expanded node. Is there any method in the api which can help with this?

Thanks in advance.

**Comment by ugurdogrusoz** [comment]
@utkarshagarwal01 this issue is not an issue of this extension. how the layout behaves depends on the layout style used, which is an option in this extension. we recommend that you use cose-bilkent with this extension. If cose-bilkent is not suitable for your application, then try to use a layout style which support incremental layout (a layout that respects current node positions, typically randomize: false).

**Comment by utkarshagarwal01** [comment]
@ugurdogrusoz Yes sir, I realize you are correct. The problem is with the dagre layout itself. 
Pity that dagre doesn't have a randomize: false option.
I'll look into your prospected solution and thank you for a clear answer.

**Comment by Remimstr** [comment]
I am using the dagre layout and ran into this exact problem. I noticed that what seemed to be causing it was dagre changing the order of the nodes and edges after an expand or collapse event. I addressed this (and solved my problem) by sorting the nodes before rendering each time.

```javascript

let api = this.cy.expandCollapse({
  layoutBy: () => {
    var processedElements = this.cy
        .elements()
        // An additional "rank" attribute is used to sort the edges and
        // nodes. This fixes an issue where the graph could rearrange itself
        // when nodes are collapsed and decollapsed
        .sort((a, b) => a.data("rank") - b.data("rank"));

    var layout = processedElements.layout({
        // We use the dagre (directed acyclic graph) layout
        // in the left-right rank to render the graph horizontally
        name: "dagre",
        rankDir: "LR",
        animate: true,
        nodeDimensionsIncludeLabels: true
    });

    layout.run();
  }
});
```

**Comment by utkarshagarwal01** [comment]
@Remimstr Hey, this could be really helpful in my use case. I'll try to implement this soon.
