### ISSUE TITLE
Should collapsed compound node still behave as "compound node"?

### ISSUE THREAD

**Issue by aindlq** [iVis-at-Bilkent/cytoscape.js-expand-collapse#7]
As I understand when node is collapsed, technically it is still a compound node and not just a simple node, right?
If so, is it necessary to keep it as compound node when it is collapsed?
The issue with compound nodes is that one can't really edit their dimensions, it is understandable when node actually has some children but it is very limiting when node is collapsed.

E.g for collapsed nodes I'm trying to put label inside the node and have node width and height aligned with label size + some padding, but currently it is doesn't work.

See http://jsbin.com/wibuzizeva/edit?output

**Comment by aindlq** [comment]
Another use case is that when nodes are collapsed I want them to be of the same size so I can put some image as a background.

**Comment by ugurdogrusoz** [comment]
@mrsfy Can we set collapsed nodes as "simple" without causing any problems so that the user is free to resize them?

**Comment by mrsfy** [comment]
@aindlq please correct if I am wrong:
In cytoscape.js, if a node has at least a child, it is parent. It sets automatically. 
Collapse operation removes all children of parent. Thus, parent becomes a simple node. Afterwards, it should be styled like a simple node.

I also ensured that `ele.isParent()` gives `false` for a collapsed node.

**Comment by aindlq** [comment]
Hm, that is really strange. I can confirm that collapsed compound node is not matched by parent selector. Why then collapsed node behave differently from simple node? E.g

http://jsbin.com/jegujezejo/edit?html,output

There is simple node, which expands to label size, it works fine. If you try to collapse compound node, I would expect the same behaviour, but it behaves differently.

It can be cytoscape bug.

**Comment by aindlq** [comment]
I can confirm that this is cytoscape bug. See http://jsbin.com/fujocekaso/1/edit?html,output

**Comment by mrsfy** [comment]
I will inspect it detailed. Also, we should report it when we understood the bug completely.

**Comment by aindlq** [comment]
Has been fixed upstream - https://github.com/cytoscape/cytoscape.js/issues/1463
