### ISSUE TITLE
Is it posssible to merge links from the same group to another node after collapse the group node

### ISSUE THREAD

**Issue by Does666** [iVis-at-Bilkent/cytoscape.js-expand-collapse#70]
Say the demo data is two groups named `group0` and `group1`,  `group0` has three children nodes named 'group0_child1' 'group0_child2' 'group0_child3' , each child of `group0` connect to `group1`.

I find that links from children of `group0` to `group1` are not merged after collapse `group0` while set 'curve-style' . 

After collapse `group0` , there are still three links from `group0` to `group1`. I expect it should be one link between `group0` and `group1`. Or is there a switch to control this behavior?

See the [demo](https://codepen.io/Does666/pen/WPLjQq).

**Comment by ugurdogrusoz** [comment]
Currently we don't support this, would like to do so in the future though.
Same as https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/issues/11
