### ISSUE TITLE
api.collapseAll() doesn't generate expandcollapse.aftercollapse event when called from cytoscape ready

### ISSUE THREAD

**Issue by utkarshagarwal01** [iVis-at-Bilkent/cytoscape.js-expand-collapse#71]
As explained in the title, the call to api.collapseAll() doesn't generate the expandcollapse event in cy.on('expandcollapse').

This issue can be seen in the library demo file [https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/blob/master/demo-compounds-collapsed.html#L57](here).

I understand it might be tough to provide an event on cytoscape when it hasn't event completely initialized yet, but maybe a callback could be provided/a promise could be returned from the call?

**Comment by kinimesi** [comment]
It does generate the event. The problem is that you are start listening for the event after the event is triggered. If you really want to capture that event, you need to listen the event in the `ready` function itself before calling `api.collapseAll`. Something like this:

```js
ready: function() {
    this.on('expandcollapse.aftercollapse', () => {
        console.log( 'after collapse'); 
    });

    var api = this.expandCollapse({
        layoutBy: {
            name: "cose-bilkent",
            animate: "end",
            randomize: false,
            fit: true
        },
        fisheye: true,
        animate: false,
        undoable: false
    });
    api.collapseAll();
}
```

**Comment by utkarshagarwal01** [comment]
Oh yeah, it makes sense now! Thanks @kinimesi +1

**Comment by utkarshagarwal01** [comment]
Also, what if i want to run some code after all the nodes have been collapsed (and not per node)? Is there some way to capture the "global" aftercollapse event?

**Comment by utkarshagarwal01** [comment]
Also, as far as i can see, the `aftercollapse` event is generated before the actual edges are removed and meta edges are added. Is this the required behaviour?
