### ISSUE TITLE
Remove dependency on jQuery

### ISSUE THREAD

**Issue by groovy21** [iVis-at-Bilkent/cytoscape.js-expand-collapse#72]
Hi,

Can we remove the dependency on jQuery please? jQuery is a heavy library and I dont see a full fledged use of that library here. Using this with npm install explicitly shows a message that jQuery is a dependency but must be installed manually. After that the bundler doesnt detect the installed jquery sometimes and has issues bundling. You might want to consider things at following for more details on why you dont need jquery.

http://youmightnotneedjquery.com/

**Comment by ugurdogrusoz** [comment]
@kinimesi Do we make heavy use of jQuery in this extension? Should we ask @groovy21 to give it a try and make a PR for this?

**Comment by kinimesi** [comment]
jQuery is used very lightly. Its functionality can be replaced with standard DOM methods easily. As far as I remember, jQuery is used only in `src/cueUtilities` and `/src/debounce.js` files.

If @groovy21 really wants to get rid of `jQuery` dependency, he/she can make a PR. It shouldn't take more than half an hour.

**Comment by groovy21** [comment]
Its not half an hour for me definitely. Given that I have to make the change and test it with some of my own examples and the ones in your demos. But I will try and send out a pull request. 

Do you have a an automated test suite for this cytoscape expand collapse?

**Comment by ugurdogrusoz** [comment]
@groovy21 please go ahead. No we dont have any tests unfortunately.

**Comment by vittoriozamboni** [comment]
Great job!

**Comment by hasanbalci** [comment]
jQuery dependency is removed in the unstable branch. jQuery-free version will be available with the new release, so closing this issue.
