### ISSUE TITLE
Cannot access the ancestors of a removed node with node.ancestors()

### ISSUE THREAD

**Issue by utkarshagarwal01** [iVis-at-Bilkent/cytoscape.js-expand-collapse#73]
The call to `node.ancestors()` return an empty collection for a removed node, as its parent is set to `null` as described below by @kinimesi

Prior to v3.4.0, we could access the parent of a removed node by using `removedEle.parent()`. But in v3.4.0, when a node is removed its parent is set to `null` That is why we never get out of the while loop.
https://github.com/cytoscape/cytoscape.js/commit/7f5b63c2483988dcc0671b500458cee0c52f3d19#diff-0a12ab28e95ef60c35904eebf53d64e7R632

I think we can get the parent node from the `parent` field of data. When [this line](https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/blob/8a2e4157def5613e0e477e393dc2c0720e41c032/src/expandCollapseUtilities.js#L607) is replaced with the following line, it works both in newer and older versions (I haven't tested it extensively):
```
 current = cy.getElementById(current.data('parent'));
```

_Originally posted by @kinimesi in https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/issues/69#issuecomment-474483088_

**Comment by hasanbalci** [comment]
@utkarshagarwal01 We now provided a new functionality in the api to reach parent of a node (`api.getParent(nodeId)`). I think you can obtain the ancestors of a removed node by using this. It is available in the unstable branch and we'll make a release soon.
