### ISSUE TITLE
How to disable auto select behavior after expand or collpase node

### ISSUE THREAD

**Issue by Does666** [iVis-at-Bilkent/cytoscape.js-expand-collapse#76]
When expand or collpase compond node, the node will be auto selected, and `select` event will be triggered. 

cy.on('select', 'node', function(evt){
  // trigger select
});

Is it possible to disable this behavior ? I expect only tapping the node obviously to trigger `select` event and expand or collapse node not to trigger `select` event .

**Comment by manotoor** [comment]
any workaround for this?

**Comment by denglouhen** [comment]
I am facing the same problem.

**Comment by code247** [comment]
Facing the same issue.

**Comment by hasanbalci** [comment]
Currently, this must be solved in unstable branch and will be available in npm with a new release. When you click on the visual cue, `select` event is not triggered and node keeps its selection status after expand-collapse operation.

**Comment by ugurdogrusoz** [comment]
Use the unstable branch to confirm the fix and let us know if you see a problem.
