### ISSUE TITLE
angular 8 works on dev mode but gives error after build

### ISSUE THREAD

**Issue by canbax** [iVis-at-Bilkent/cytoscape.js-expand-collapse#77]
It occurs when I get a build using angular.
![image](https://user-images.githubusercontent.com/8426741/60101055-b70ab700-9763-11e9-86b2-604f255afdd3.png)

I think problem is here
https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/blob/8a2e4157def5613e0e477e393dc2c0720e41c032/src/cueUtilities.js#L278

`Tap = function (event) { ` should have been `eTap = function (event) { ` because `Tap` is not defined but `eTap` is defined but never assigned.

**Comment by hasanbalci** [comment]
@canbax Can you test and verify the fix in unstable branch?

**Comment by canbax** [comment]
I used unstable branch, it looks ok
