### ISSUE TITLE
Update Cytoscape.js dependency

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/cytoscape.js-expand-collapse#82]
Extension is problematic with Cytoscape.js versions 2.x and the recommended layout extension (cose-bilkent) supports Cytoscape.js ^3.2.0. Therefore, it would be good to change Cytoscape.js dependency of this extension as ^3.2.0 both in package.json and README.

Also, let's use the latest version of cose-bilkent in demo files.

**Edit:** The extension gives the same error [here](https://github.com/cytoscape/cytoscape.js-edgehandles/issues/85) in Cytoscape.js v3.2.0. But it's fixed in the later versions. To be more conservative, we can change the dependency as ^3.3.0.

**Comment by nasimsaleh** [comment]
i updated dependency to ^3.3.0

**Comment by ugurdogrusoz** [comment]
@hasanbalci pls check and close if OK
