### ISSUE TITLE
User-defined cue images are not drawn in correct position

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/cytoscape.js-expand-collapse#83]
Default image: 
<img src="https://user-images.githubusercontent.com/22586369/64180417-67382280-ce6d-11e9-991f-243dbc017776.png" width="200" height="200" />

User-defined image: 
<img src="https://user-images.githubusercontent.com/22586369/64180985-5d62ef00-ce6e-11e9-8ff3-d694afc4c6be.png" width="200" height="200" />

Therefore, clicking on the user-defined image may not trigger the required operation, while clicking on the empty space on the top-left works.

**Comment by nasimsaleh** [comment]
It was bug with the usage of the 'drawImage' function parameters
Also found another minor bug where the option 'collapseCueImage' was dealt with as the expand cue image and vice versa. all fixed now

**Comment by ugurdogrusoz** [comment]
@hasanbalci pls check and close if OK

**Comment by hasanbalci** [comment]
@nasimsaleh Why did you change the previous default cue images?
