### ISSUE TITLE
Revisit visual cue rendering and hit testing

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-expand-collapse#86]
We've had many varying problems with visual cues in the past. I think we should change the way we display and listen to visual cues being clicked on. Similar to node resize extension, let's display expand-collapse visual cues only when a (single) node is in selected state. Then, detecting the hit of these visual cues should be easier (similar to resize handles in node resize extension).

**Comment by ugurdogrusoz** [comment]
As far as I could test with the demo and the daily Newt, I see the following problems:
- [ ] 1. Compound nodes will not show the visual cue for collapse **the first time** they are selected. After the first time, things look fine.
- [ ] 2. If a node is selected and the zoom level changes, we lose the visual cue for expand/collapse (unlike the resize handles and the resize node to content cue).
- [ ] 3. When a node is collapsed (expanded), the node stay selected after the operation but no expand (collapse) cue is displayed.

**Comment by hasanbalci** [comment]
It seems ok, so I'm closing.
