### ISSUE TITLE
Compound edge clipping problem in demo

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-expand-collapse#87]
In our demo where compounds are initially collapsed, the edges incident to compounds are not clipped properly. They go all the way to the center of the compound as opposed to being clipped on the edge of the node:
<img width="247" alt="Screenshot 2019-09-12 at 19 59 26" src="https://user-images.githubusercontent.com/3874988/64804876-6a7f8c80-d598-11e9-9044-cb1258a79813.png">

**Comment by nasimsaleh** [comment]
Haystack edge type does not support compound nodes as stated [here](http://js.cytoscape.org/#style/edge-line). and 'haystack' is the default value for the edge curve style. Changed it now in the demo to 'straight' style and it works, I also tried it with all other curve styles and there are no problems.
