### ISSUE TITLE
expandCueImage not working on the latest version 3.2.0 in Chrome dev mode

### ISSUE THREAD

**Issue by Does666** [iVis-at-Bilkent/cytoscape.js-expand-collapse#90]
I download the latest version and run the offical demo `demo.html`, unfortunately  the `expandCueImage`  not show. When I comment out `expandCueImage` and `collapseCueImage`, it works well to show the default cue. 

After try out many times , I find that this case only occurs when open Chorme F12 develop tool. When close the develop tool, the issue disappear. It looks magic .

Does anybody meet this issue ? Is it a bug ?

A

**Comment by hasanbalci** [comment]
@Does666 I cannot reproduce this issue. Can you please specify your OS and browser specifications?

**Comment by Does666** [comment]
@hasanbalci  OS ： Window10 (1903)  Chrome : 79.0.3945.88 (32bit)

**Comment by Does666** [comment]
@hasanbalci Can you reproduce this issue ? My buddies could also reproduce it with Chrome by opening dev mode.

**Comment by hasanbalci** [comment]
@Does666 As you can see in the gif, it works well while devTools is open with my Windows 10, Chrome 79.0.3945.117 (64-bit) setting. Unfortunately, I don't know why it doesn't work in your case or what can be the solution. 
![cue-indevmode](https://user-images.githubusercontent.com/22586369/72548322-7e693100-389f-11ea-9f26-1495b1c5b5c0.gif)
