### ISSUE TITLE
Events for edge expand-collapse

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/cytoscape.js-expand-collapse#95]
Currently, extension has [events](https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse#events) that are performed for each node that is collapsed/expanded. In the same way, event support for collapsed/expanded edges can be added.

**Comment by ugurdogrusoz** [comment]
@hasanbalci Please check and close if OK.

**Comment by hasanbalci** [comment]
`beforeCollapseEdge` and `afterCollapseEdge` events are ok, but it seems that `beforeExpandEdge` and `afterExpandEdge` are not very useful currently. If user defines these events one time on the current edges while there is no meta edge, and then create meta edges by collapsing some edges, since meta edges are newly created they won't have these events. User will need to define these events each time a new meta edge is created which is not so convenient. Maybe we can keep them for now and reconsider later if someone encounter with an issue. 

By the way, the naming of the events are not consistent with the ones for nodes. For nodes, all lowercase is used while it is camel case for edges (`beforecollapse` and `beforeCollapseEdge`). To be consistent, we can use either all lowercase or camel case for all event names.

**Comment by ugurdogrusoz** [comment]
- @canbax do you see a way to eliminate the problem mentioned by @hasanbalci ?

- Use of came case is nicer but would break backward compatibility. Let's consistently use all lower case.

**Comment by canbax** [comment]
I think a user should not define these events on elements. [Here is the event I mentioned](https://js.cytoscape.org/#eles.on)

If the user should call a function each time an expand-collapse occurs, they should listen for [events occurring on the core cy](https://js.cytoscape.org/#cy.on)

Maybe this won't be enough for some cases but I can't think of an example.

**Comment by hasanbalci** [comment]
Then, maybe we can change the documentation of the events to 
`cy.on("expandcollapse.beforecollapse", function(event) { var node = event.target; ... })` for nodes and
`cy.on("expandcollapse.beforecollapseedge", function(event) { var edge = event.target; ... })` for edges.
