### ISSUE TITLE
No nested edge collapse

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-expand-collapse#96]
The extension seems to allow and correctly handle nested edge collapse. In other words, one can collapse say 3 of the 5 multi edges between the same pair of nodes, and then collapse again the remaining 2 original edges with the meta edge resulting from the previous collapse operation. While this may be useful, some applications would prefer to see original edges collapsed directly inside visible meta edges as opposed to being nested deeply as described above.
To allow this use case, let's add a new extension option named `allowNestedEdgeCollapse`. When this option is true, the extension behaves as it does now. When it's false, however, when a meta edge is in the set of edges to be collapsed, we should first expand this meta edge and add the corresponding original edges to the set of edges to be collapsed instead of this meta edge. All these operations should be done as a batch, not doing any redundant rendering (i.e. the user should not see an explicit expand followed by a collapse).

**Comment by ugurdogrusoz** [comment]
Seems to work nicely. @hasanbalci Pls check as well and close if OK.

**Comment by hasanbalci** [comment]
It seems ok, only new option should be added to README -> Default Options, then we can close it.
